export const clients = [
  { id: "12", name: "ahmed" },
  { id: "15", name: "lina rosa" },
  { id: "5", name: "albert jhon" },
  { id: "10", name: "abdel" },
  { id: "19", name: "lucie grandi" },
  { id: "3", name: "jhone week" },
  { id: "22", name: "saadia" },
  { id: "24", name: "yassine" },
  { id: "77", name: "morad" },
];

export const technicienStats = [
  {
    name: "Said",
    ticketsFeremeCeMois: 8,
    ticketsFeremeCetteAnnee: 45,
    moyenneInterventionsCeMois: "2h15",
    moyenneInterventionsCetteAnnee: "2h38",
  },
  {
    name: "Ali",
    ticketsFeremeCeMois: 5,
    ticketsFeremeCetteAnnee: 38,
    moyenneInterventionsCeMois: "1h45",
    moyenneInterventionsCetteAnnee: "2h10",
  },
  {
    name: "Omar",
    ticketsFeremeCeMois: 7,
    ticketsFeremeCetteAnnee: 52,
    moyenneInterventionsCeMois: "2h30",
    moyenneInterventionsCetteAnnee: "2h25",
  },
  {
    name: "Fatima",
    ticketsFeremeCeMois: 6,
    ticketsFeremeCetteAnnee: 41,
    moyenneInterventionsCeMois: "1h55",
    moyenneInterventionsCetteAnnee: "2h15",
  },
  {
    name: "Hassan",
    ticketsFeremeCeMois: 9,
    ticketsFeremeCetteAnnee: 47,
    moyenneInterventionsCeMois: "2h20",
    moyenneInterventionsCetteAnnee: "2h42",
  },
  {
    name: "Nadia",
    ticketsFeremeCeMois: 4,
    ticketsFeremeCetteAnnee: 35,
    moyenneInterventionsCeMois: "1h50",
    moyenneInterventionsCetteAnnee: "2h05",
  },
  {
    name: "Amine",
    ticketsFeremeCeMois: 6,
    ticketsFeremeCetteAnnee: 39,
    moyenneInterventionsCeMois: "2h10",
    moyenneInterventionsCetteAnnee: "2h30",
  },
  {
    name: "Zara",
    ticketsFeremeCeMois: 3,
    ticketsFeremeCetteAnnee: 28,
    moyenneInterventionsCeMois: "1h40",
    moyenneInterventionsCetteAnnee: "2h00",
  },
  {
    name: "Samir",
    ticketsFeremeCeMois: 5,
    ticketsFeremeCetteAnnee: 43,
    moyenneInterventionsCeMois: "2h25",
    moyenneInterventionsCetteAnnee: "2h35",
  },
  {
    name: "Rachid",
    ticketsFeremeCeMois: 4,
    ticketsFeremeCetteAnnee: 31,
    moyenneInterventionsCeMois: "2h05",
    moyenneInterventionsCetteAnnee: "2h20",
  },
];
export const tickets = [
  {
    type: "Maintenance",
    numeroTicket: "T001",
    numeroSerie: "SN001",
    designation: "Problème d'imprimante",
    clientId: "12", // Reference to the client with id 12 (ahmed)
    dateOuverture: "2024-01-01",
    SLA: 2,
    dureeAppel: 45,
    dateAffectation: "2024-01-02",
    compteurMono: 150,
    compteurCouleur: 30,
    statut: "Fermé",
    dateFermeture: "2024-01-04",
    dureeTicket: 3,
    technicien: "Said",
    tauxSLA: 100,
  },
  {
    type: "Réseau",
    numeroTicket: "T002",
    numeroSerie: "SN002",
    designation: "Problème de routeur",
    clientId: "15", // Reference to the client with id 15 (lina rosa)
    dateOuverture: "2024-10-15",
    SLA: 1,
    dureeAppel: 30,
    dateAffectation: "2024-11-05",
    compteurMono: 200,
    compteurCouleur: 50,
    statut: "Ouvert",
    dateFermeture: null,
    dureeTicket: null,
    technicien: "Ali",
    tauxSLA: null,
  },
  {
    type: "Logiciel",
    numeroTicket: "T003",
    numeroSerie: "SN003",
    designation: "Mise à jour du logiciel",
    clientId: "15", // Reference to the client with id 15 (lina rosa)
    dateOuverture: "2024-01-01",
    SLA: 3,
    dureeAppel: 60,
    dateAffectation: "2024-01-11",
    compteurMono: 250,
    compteurCouleur: 80,
    statut: "Fermé",
    dateFermeture: "2024-01-12",
    dureeTicket: 2,
    technicien: "Omar",
    tauxSLA: 100,
  },
  {
    type: "Sécurité",
    numeroTicket: "T004",
    numeroSerie: "SN004",
    designation: "Problème de pare-feu",
    clientId: "5", // Reference to the client with id 5 (albert jhon)
    dateOuverture: "2024-01-16",
    SLA: 2,
    dureeAppel: 20,
    dateAffectation: "2024-01-16",
    compteurMono: 180,
    compteurCouleur: 40,
    statut: "Fermé",
    dateFermeture: "2024-02-17",
    dureeTicket: 2,
    technicien: "Fatima",
    tauxSLA: 100,
  },
  {
    type: "Infrastructure",
    numeroTicket: "T005",
    numeroSerie: "SN005",
    designation: "Problème de serveur",
    clientId: "10", // Reference to the client with id 10 (abdel)
    dateOuverture: "2024-10-15",
    SLA: 5,
    dureeAppel: 90,
    dateAffectation: "2024-01-16",
    compteurMono: 300,
    compteurCouleur: 60,
    statut: "Ouvert",
    dateFermeture: null,
    dureeTicket: null,
    technicien: "Hassan",
    tauxSLA: null,
  },
  {
    type: "Matériel",
    numeroTicket: "T006",
    numeroSerie: "SN006",
    designation: "Remplacement de matériel",
    clientId: "19", // Reference to the client with id 19 (lucie grandi)
    dateOuverture: "2023-01-22",
    SLA: 3,
    dureeAppel: 50,
    dateAffectation: "2023-01-23",
    compteurMono: 210,
    compteurCouleur: 55,
    statut: "Fermé",
    dateFermeture: "2023-01-30",
    dureeTicket: 2,
    technicien: "Nadia",
    tauxSLA: 100,
  },
  {
    type: "Assistance",
    numeroTicket: "T007",
    numeroSerie: "SN007",
    designation: "Assistance technique",
    clientId: "3", // Reference to the client with id 3 (jhone week)
    dateOuverture: "2023-01-25",
    SLA: 1,
    dureeAppel: 30,
    dateAffectation: "2023-01-25",
    compteurMono: 120,
    compteurCouleur: 35,
    statut: "Fermé",
    dateFermeture: "2023-01-26",
    dureeTicket: 1,
    technicien: "Amine",
    tauxSLA: 100,
  },
  {
    type: "Formation",
    numeroTicket: "T008",
    numeroSerie: "SN008",
    designation: "Formation utilisateur",
    clientId: "22", // Reference to the client with id 22 (saadia)
    dateOuverture: "2024-07-27",
    SLA: 7,
    dureeAppel: 120,
    dateAffectation: "2024-07-28",
    compteurMono: 300,
    compteurCouleur: 80,
    statut: "Ouvert",
    dateFermeture: null,
    dureeTicket: null,
    technicien: "Zara",
    tauxSLA: null,
  },
  {
    type: "Upgrade",
    numeroTicket: "T009",
    numeroSerie: "SN009",
    designation: "Mise à niveau de l'application",
    clientId: "24", // Reference to the client with id 24 (yassine)
    dateOuverture: "2024-02-01",
    SLA: 4,
    dureeAppel: 75,
    dateAffectation: "2024-03-30",
    compteurMono: 250,
    compteurCouleur: 70,
    statut: "Fermé",
    dateFermeture: "2024-02-11",
    dureeTicket: 3,
    technicien: "Samir",
    tauxSLA: 100,
  },
  {
    type: "Installation",
    numeroTicket: "T010",
    numeroSerie: "SN010",
    designation: "Installation de nouveaux équipements",
    clientId: "77", // Reference to the client with id 77 (morad)
    dateOuverture: "2024-10-16",
    SLA: 2,
    dureeAppel: 100,
    dateAffectation: "2024-05-03",
    compteurMono: 220,
    compteurCouleur: 60,
    statut: "Ouvert",
    dateFermeture: null,
    dureeTicket: null,
    technicien: "Rachid",
    tauxSLA: null,
  },
  {
    type: "Maintenance",
    numeroTicket: "T011",
    numeroSerie: "SN011",
    designation: "Problème de scanner",
    clientId: "12",
    dateOuverture: "2024-02-15",
    SLA: 2,
    dureeAppel: 35,
    dateAffectation: "2024-02-15",
    compteurMono: 175,
    compteurCouleur: 45,
    statut: "Fermé",
    dateFermeture: "2024-02-17",
    dureeTicket: 2,
    technicien: "Said",
    tauxSLA: 100,
  },
  {
    type: "Réseau",
    numeroTicket: "T012",
    numeroSerie: "SN012",
    designation: "Configuration switch",
    clientId: "15",
    dateOuverture: "2024-03-01",
    SLA: 3,
    dureeAppel: 55,
    dateAffectation: "2024-03-01",
    compteurMono: 280,
    compteurCouleur: 65,
    statut: "Fermé",
    dateFermeture: "2024-03-03",
    dureeTicket: 2,
    technicien: "Omar",
    tauxSLA: 100,
  },
  {
    type: "Logiciel",
    numeroTicket: "T013",
    numeroSerie: "SN013",
    designation: "Installation antivirus",
    clientId: "5",
    dateOuverture: "2024-10-18",
    SLA: 1,
    dureeAppel: 40,
    dateAffectation: "2024-10-18",
    compteurMono: 190,
    compteurCouleur: 25,
    statut: "Ouvert",
    dateFermeture: null,
    dureeTicket: null,
    technicien: "Ali",
    tauxSLA: null,
  },
  {
    type: "Maintenance",
    numeroTicket: "T014",
    numeroSerie: "SN014",
    designation: "Remplacement toner",
    clientId: "19",
    dateOuverture: "2024-03-10",
    SLA: 1,
    dureeAppel: 25,
    dateAffectation: "2024-03-10",
    compteurMono: 220,
    compteurCouleur: 50,
    statut: "Fermé",
    dateFermeture: "2024-03-11",
    dureeTicket: 1,
    technicien: "Fatima",
    tauxSLA: 100,
  },
  {
    type: "Infrastructure",
    numeroTicket: "T015",
    numeroSerie: "SN015",
    designation: "Maintenance serveur",
    clientId: "22",
    dateOuverture: "2024-03-15",
    SLA: 4,
    dureeAppel: 120,
    dateAffectation: "2024-03-15",
    compteurMono: 310,
    compteurCouleur: 85,
    statut: "Fermé",
    dateFermeture: "2024-03-18",
    dureeTicket: 3,
    technicien: "Hassan",
    tauxSLA: 100,
  },
  {
    type: "Sécurité",
    numeroTicket: "T016",
    numeroSerie: "SN016",
    designation: "Mise à jour sécurité",
    clientId: "24",
    dateOuverture: "2024-03-20",
    SLA: 2,
    dureeAppel: 45,
    dateAffectation: "2024-03-20",
    compteurMono: 240,
    compteurCouleur: 55,
    statut: "Fermé",
    dateFermeture: "2024-03-21",
    dureeTicket: 1,
    technicien: "Said",
    tauxSLA: 100,
  },
  {
    type: "Formation",
    numeroTicket: "T017",
    numeroSerie: "SN017",
    designation: "Formation logiciel",
    clientId: "77",
    dateOuverture: "2024-10-19",
    SLA: 5,
    dureeAppel: 180,
    dateAffectation: "2024-10-19",
    compteurMono: 290,
    compteurCouleur: 75,
    statut: "Ouvert",
    dateFermeture: null,
    dureeTicket: null,
    technicien: "Omar",
    tauxSLA: null,
  },
  {
    type: "Maintenance",
    numeroTicket: "T018",
    numeroSerie: "SN018",
    designation: "Calibrage imprimante",
    clientId: "12",
    dateOuverture: "2024-04-01",
    SLA: 2,
    dureeAppel: 60,
    dateAffectation: "2024-04-01",
    compteurMono: 200,
    compteurCouleur: 40,
    statut: "Fermé",
    dateFermeture: "2024-04-02",
    dureeTicket: 1,
    technicien: "Nadia",
    tauxSLA: 100,
  },
  {
    type: "Réseau",
    numeroTicket: "T019",
    numeroSerie: "SN019",
    designation: "Configuration VPN",
    clientId: "15",
    dateOuverture: "2024-04-05",
    SLA: 3,
    dureeAppel: 90,
    dateAffectation: "2024-04-05",
    compteurMono: 260,
    compteurCouleur: 70,
    statut: "Fermé",
    dateFermeture: "2024-04-07",
    dureeTicket: 2,
    technicien: "Amine",
    tauxSLA: 100,
  },
  {
    type: "Logiciel",
    numeroTicket: "T020",
    numeroSerie: "SN020",
    designation: "Installation suite bureautique",
    clientId: "10",
    dateOuverture: "2024-04-10",
    SLA: 1,
    dureeAppel: 45,
    dateAffectation: "2024-04-10",
    compteurMono: 230,
    compteurCouleur: 45,
    statut: "Fermé",
    dateFermeture: "2024-04-11",
    dureeTicket: 1,
    technicien: "Hassan",
    tauxSLA: 100,
  },
  {
    type: "Maintenance",
    numeroTicket: "T021",
    numeroSerie: "SN021",
    designation: "Nettoyage équipement",
    clientId: "19",
    dateOuverture: "2024-04-15",
    SLA: 2,
    dureeAppel: 30,
    dateAffectation: "2024-04-15",
    compteurMono: 185,
    compteurCouleur: 35,
    statut: "Fermé",
    dateFermeture: "2024-04-16",
    dureeTicket: 1,
    technicien: "Samir",
    tauxSLA: 100,
  },
  {
    type: "Infrastructure",
    numeroTicket: "T022",
    numeroSerie: "SN022",
    designation: "Mise à jour système",
    clientId: "3",
    dateOuverture: "2024-04-20",
    SLA: 4,
    dureeAppel: 150,
    dateAffectation: "2024-04-20",
    compteurMono: 320,
    compteurCouleur: 90,
    statut: "Fermé",
    dateFermeture: "2024-04-23",
    dureeTicket: 3,
    technicien: "Fatima",
    tauxSLA: 100,
  },
  {
    type: "Sécurité",
    numeroTicket: "T023",
    numeroSerie: "SN023",
    designation: "Audit sécurité",
    clientId: "22",
    dateOuverture: "2024-10-17",
    SLA: 5,
    dureeAppel: 240,
    dateAffectation: "2024-10-17",
    compteurMono: 275,
    compteurCouleur: 65,
    statut: "Ouvert",
    dateFermeture: null,
    dureeTicket: null,
    technicien: "Ali",
    tauxSLA: null,
  },
  {
    type: "Formation",
    numeroTicket: "T024",
    numeroSerie: "SN024",
    designation: "Formation sécurité",
    clientId: "24",
    dateOuverture: "2024-05-01",
    SLA: 3,
    dureeAppel: 180,
    dateAffectation: "2024-05-01",
    compteurMono: 245,
    compteurCouleur: 60,
    statut: "Fermé",
    dateFermeture: "2024-05-03",
    dureeTicket: 2,
    technicien: "Omar",
    tauxSLA: 100,
  },
  {
    type: "Maintenance",
    numeroTicket: "T025",
    numeroSerie: "SN025",
    designation: "Dépannage scanner",
    clientId: "77",
    dateOuverture: "2024-05-05",
    SLA: 2,
    dureeAppel: 40,
    dateAffectation: "2024-05-05",
    compteurMono: 210,
    compteurCouleur: 45,
    statut: "Fermé",
    dateFermeture: "2024-05-06",
    dureeTicket: 1,
    technicien: "Said",
    tauxSLA: 100,
  },
  {
    type: "Réseau",
    numeroTicket: "T026",
    numeroSerie: "SN026",
    designation: "Configuration réseau",
    clientId: "12",
    dateOuverture: "2024-05-10",
    SLA: 3,
    dureeAppel: 75,
    dateAffectation: "2024-05-10",
    compteurMono: 295,
    compteurCouleur: 80,
    statut: "Fermé",
    dateFermeture: "2024-05-12",
    dureeTicket: 2,
    technicien: "Nadia",
    tauxSLA: 100,
  },
  {
    type: "Logiciel",
    numeroTicket: "T027",
    numeroSerie: "SN027",
    designation: "Mise à jour logiciel",
    clientId: "15",
    dateOuverture: "2024-10-16",
    SLA: 2,
    dureeAppel: 55,
    dateAffectation: "2024-10-16",
    compteurMono: 225,
    compteurCouleur: 50,
    statut: "Ouvert",
    dateFermeture: null,
    dureeTicket: null,
    technicien: "Hassan",
    tauxSLA: null,
  },
  {
    type: "Maintenance",
    numeroTicket: "T028",
    numeroSerie: "SN028",
    designation: "Maintenance préventive",
    clientId: "5",
    dateOuverture: "2024-05-20",
    SLA: 4,
    dureeAppel: 120,
    dateAffectation: "2024-05-20",
    compteurMono: 330,
    compteurCouleur: 95,
    statut: "Fermé",
    dateFermeture: "2024-05-23",
    dureeTicket: 3,
    technicien: "Amine",
    tauxSLA: 100,
  },
  {
    type: "Infrastructure",
    numeroTicket: "T029",
    numeroSerie: "SN029",
    designation: "Optimisation serveur",
    clientId: "10",
    dateOuverture: "2024-05-25",
    SLA: 3,
    dureeAppel: 160,
    dateAffectation: "2024-05-25",
    compteurMono: 285,
    compteurCouleur: 75,
    statut: "Fermé",
    dateFermeture: "2024-05-27",
    dureeTicket: 2,
    technicien: "Samir",
    tauxSLA: 100,
  },
  {
    type: "Sécurité",
    numeroTicket: "T030",
    numeroSerie: "SN030",
    designation: "Installation firewall",
    clientId: "19",
    dateOuverture: "2024-10-18",
    SLA: 2,
    dureeAppel: 90,
    dateAffectation: "2024-10-18",
    compteurMono: 250,
    compteurCouleur: 55,
    statut: "Ouvert",
    dateFermeture: null,
    dureeTicket: null,
    technicien: "Fatima",
    tauxSLA: null,
  },
];
